return {
  "johmsalas/text-case.nvim",
  event = "BufReadPost",
  -- stylua: ignore
  keys = {
    { "gtl", '<cmd>lua require("textcase").current_word("to_lower_case")<cr>', mode = { "n" , "v" }, desc = "lowercase" },
    { "gtu", '<cmd>lua require("textcase").current_word("to_upper_case")<cr>', mode = { "n" , "v" }, desc = "UPPERCASE" },
    { "gtp", '<cmd>lua require("textcase").current_word("to_pascal_case")<cr>', mode = { "n" , "v" }, desc = "PascalCase" },
    { "gtc", '<cmd>lua require("textcase").current_word("to_camel_case")<cr>', mode = { "n" , "v" }, desc = "camelCase" },
    { "gts", '<cmd>lua require("textcase").current_word("to_snake_case")<cr>', mode = { "n" , "v" }, desc = "snake_case" },
    { "gtS", '<cmd>lua require("textcase").current_word("to_constant_case")<cr>', mode = { "n" , "v" }, desc = "SCREAMING_SNAKE_CASE" },
    { "gtk", '<cmd>lua require("textcase").current_word("to_dash_case")<cr>', mode = { "n" , "v" }, desc = "kebab-case" },
    { "gtf", '<cmd>lua require("textcase").current_word("to_path_case")<cr>', mode = { "n" , "v" }, desc = "path/case" },
    { "gtd", '<cmd>lua require("textcase").current_word("to_dot_case")<cr>', mode = { "n" , "v" }, desc = "dot.case" },
    { "gtt", '<cmd>lua require("textcase").current_word("to_title_case")<cr>', mode = { "n" , "v" }, desc = "Title Case" },
    { "gtn", '<cmd>lua require("textcase").current_word("to_phrase_case")<cr>', mode = { "n" , "v" }, desc = "Phrase case" },

    { "gll", '<cmd>lua require("textcase").lsp_rename("to_lower_case")<cr>', mode = { "n" , "v" }, desc = "lowercase" },
    { "glu", '<cmd>lua require("textcase").lsp_rename("to_upper_case")<cr>', mode = { "n" , "v" }, desc = "UPPERCASE" },
    { "glp", '<cmd>lua require("textcase").lsp_rename("to_pascal_case")<cr>', mode = { "n" , "v" }, desc = "PascalCase" },
    { "glc", '<cmd>lua require("textcase").lsp_rename("to_camel_case")<cr>', mode = { "n" , "v" }, desc = "camelCase" },
    { "gls", '<cmd>lua require("textcase").lsp_rename("to_snake_case")<cr>', mode = { "n" , "v" }, desc = "snake_case" },
    { "glS", '<cmd>lua require("textcase").lsp_rename("to_constant_case")<cr>', mode = { "n" , "v" }, desc = "SCREAMING_SNAKE_CASE" },
    { "glk", '<cmd>lua require("textcase").lsp_rename("to_dash_case")<cr>', mode = { "n" , "v" }, desc = "kebab-case" },
    { "glf", '<cmd>lua require("textcase").lsp_rename("to_path_case")<cr>', mode = { "n" , "v" }, desc = "path/case" },
    { "gld", '<cmd>lua require("textcase").lsp_rename("to_dot_case")<cr>', mode = { "n" , "v" }, desc = "dot.case" },
    { "glt", '<cmd>lua require("textcase").lsp_rename("to_title_case")<cr>', mode = { "n" , "v" }, desc = "Title Case" },
    { "gln", '<cmd>lua require("textcase").lsp_rename("to_phrase_case")<cr>', mode = { "n" , "v" }, desc = "Phrase case" },

    { "gol", '<cmd>lua require("textcase").operator("to_lower_case")<cr>', mode = { "n" , "v" }, desc = "lowercase" },
    { "gou", '<cmd>lua require("textcase").operator("to_upper_case")<cr>', mode = { "n" , "v" }, desc = "UPPERCASE" },
    { "gop", '<cmd>lua require("textcase").operator("to_pascal_case")<cr>', mode = { "n" , "v" }, desc = "PascalCase" },
    { "goc", '<cmd>lua require("textcase").operator("to_camel_case")<cr>', mode = { "n" , "v" }, desc = "camelCase" },
    { "gos", '<cmd>lua require("textcase").operator("to_snake_case")<cr>', mode = { "n" , "v" }, desc = "snake_case" },
    { "goS", '<cmd>lua require("textcase").operator("to_constant_case")<cr>', mode = { "n" , "v" }, desc = "SCREAMING_SNAKE_CASE" },
    { "gok", '<cmd>lua require("textcase").operator("to_dash_case")<cr>', mode = { "n" , "v" }, desc = "kebab-case" },
    { "gof", '<cmd>lua require("textcase").operator("to_path_case")<cr>', mode = { "n" , "v" }, desc = "path/case" },
    { "god", '<cmd>lua require("textcase").operator("to_dot_case")<cr>', mode = { "n" , "v" }, desc = "dot.case" },
    { "got", '<cmd>lua require("textcase").operator("to_title_case")<cr>', mode = { "n" , "v" }, desc = "Title Case" },
    { "gon", '<cmd>lua require("textcase").operator("to_phrase_case")<cr>', mode = { "n" , "v" }, desc = "Phrase case" },
  },
}
